var path = require('path');
var express = require('express');

var app = express();

var staticPath = path.join(__dirname, './build');
console.log(staticPath);
app.use(express.static(staticPath));

process.on('uncaughtException', function (err) {
    console.error('Uncaught Exception: ' + err.message + '\r\n' + err.stack);
});

app.get('/example-rest-api', function (req, res) {
	res.json({ hello: 'computer'});
});

app.get('/test', function (req, res) {
	res.send("<p>This web page was generated by NodeJS.</p>\n<p>The current time is: " + moment().format('HH:mm:ss') + "</p>");	
});

var server = app.listen(process.env.PORT || 3000, function () {

	var host = server.address().address
	var port = server.address().port

	console.log('Example app listening at http://%s:%s', host, port);
});
